name: Update README file
on: 
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
  contents: write 
  pages: write
  id-token: write

jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Checkout
              uses: actions/checkout@v3.0.0
              with:
                fetch-depth: 0

            - name: Restore Timestamps
              uses: chetan/git-restore-mtime-action@v1
            
            - name: Set Timezone
              uses: szenius/set-timezone@v1.2
              with:
                timezoneLinux: "America/Los_Angeles"
                # timezoneWindows: "Pacific Standard Time"

            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Install Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            
            - name: Install Dependencies
              run: pip install -r requirements.txt
              shell: bash

            - name: Update chart
              id: update_chart
              run: python ./_doc_builder/contribute_image.py
              shell: bash
            
             - name: Update file name
              id: update_file_name
              run: python ./_doc_builder/update_file_name.py
              shell: bash

            - name: Update readme
              id: update_readme
              run: python ./_doc_builder/update_readme.py
              shell: bash

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: README.md
                  commit-msg: Update README.md
                  github-token: ${{ secrets.GITHUB_TOKEN }}
